title: JD Gardner
description: High-fidelity product visions across AI, AR, and interactive media.
baseurl: ""

author:
  name: JD Gardner
  email: hello@jdgardner.xyz
  github: knifecatcher
  linkedin: jdgardner92

markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - ref/
  - _site/
